version: 0.1.0.{build}
pull_requests:
  do_not_increment_build_number: true
image: Visual Studio 2017
configuration: Release
init:
- ps: >-
    $env:nuget_version = "$env:appveyor_build_version"

    if($env:appveyor_repo_tag -eq $true) {
      $env:nuget_version = "$env:appveyor_repo_tag_name"
    } else {
      $env:nuget_version = "$env:appveyor_build_version-dev"
    }
assembly_info:
  patch: true
  file: '**\AssemblyInfo.*'
  assembly_version: '{version}'
  assembly_file_version: '{version}'
  assembly_informational_version: $(nuget_version)
before_build:
- cmd: nuget restore
build:
  verbosity: minimal
before_package:
- ps: nuget pack $env:appveyor_build_folder/ServerCommandProxy/ServerCommandProxy.csproj -version $env:nuget_version
artifacts:
- path: '**\ServerCommandProxy.*.nupkg'
  name: Papercut ServerCommandProxy
